version: '3'

services:
  
  apache:
    container_name: apache
    image: httpd:latest
    volumes:
      - ./www:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    networks:
      default:
        ipv4_address: 172.99.99.3

  php:
    build:
      ./php
    container_name: php
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql-server

  mysql-server:
    container_name: mysql-server
    image: mysql:latest
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
    volumes:
      - ./db_data/mysql:/var/lib/mysql:rw
    networks:
      default:
        ipv4_address: 172.99.99.2

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-server
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_pwd
    depends_on:
      - mysql-server
    networks:
      default:
        ipv4_address: 172.99.99.4

networks:
  default:
    name: lamp-network
    external: true
