scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
    
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://znotes.ru
        - https://pass.znotes.ru
        - https://cloud.znotes.ru
        - https://mail.znotes.ru/SOGo
        - https://mail.znotes.ru
        - https://zabbix.znotes.ru
        - https://npm.znotes.ru
        - https://portainer.znotes.ru
        - https://pma.znotes.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

