version: '3.8'
services:

  mysql-server:
    container_name: mysql-server
    image: mysql:latest
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
    volumes:
      - ./db_data/mysql:/var/lib/mysql:rw
    networks:
      default:
        ipv4_address: 172.44.1.2

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-server
      - PMA_PORT=3306
    networks:
      default:
        ipv4_address: 172.44.1.3

networks:
  default:
    name: mysql-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.1.0/24