version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host('nginx.myhost.tu')"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
networks:
  default:
    name: mynet