version: '3.8'
services:

  zabbix-server-mysql:
    container_name: zabbix-server-mysql
    image: zabbix/zabbix-server-mysql:ubuntu-6.4-latest
    restart: unless-stopped
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=root_pwd
    volumes:
      - ./zbx_data/etc/zabbix:/etc/zabbix:rw
      - ./data/export:/var/lib/zabbix/export
      - ./data/snmptraps:/var/lib/zabbix/snmptraps
    networks:
      default:
        ipv4_address: 172.44.1.6

  zabbix-web-apache-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-apache-mysql:ubuntu-6.4-latest
    restart: unless-stopped
    ports:
      - 8081:8080
      - 8443:8443
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=root_pwd
      - PHP_TZ=Europe/Moscow
      - ZBX_MEMORYLIMIT=128M
    networks:
      default:
        ipv4_address: 172.44.1.7

networks:
  default:
    name: mysql-net
    external: true
