version: '3.1'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8185:80
    environment:
      WORDPRESS_DB_HOST: mysql-server
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root_pwd
      WORDPRESS_DB_NAME: znotes_wp
    volumes:
      - ./wp-data:/var/www/html
    networks:
      default:
        ipv4_address: 172.44.1.5

networks:
  default:
    name: mysql-net
    external: true
